package com.narendra.sams.web.utils;

public enum LoggedInUserAuthority {
    ROLE_ENQUIRY_ADD_EDIT,
    ROLE_ENQUIRY_EXPORT_EXCEL,
    ROLE_ENQUIRY_ASSIGN_OWNER,
    ROLE_ENQUIRY_ASSIGN_ASSIGNEE,
    ROLE_ENQUIRY_FOLLOW,
    ROLE_ENQUIRY_VIEW_ALL,
    ROLE_ENQUIRY_VIEW_OWN,
    ROLE_ENQUIRY_TAB
}
